INFO: loading config from ss.json
Traceback (most recent call last):
  File "/usr/bin/sslocal", line 11, in <module>
    load_entry_point('shadowsocks==2.9.0', 'console_scripts', 'sslocal')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/local.py", line 39, in main
    config = shell.get_config(True)
  File "/usr/lib/python2.7/dist-packages/shadowsocks/shell.py", line 151, in get_config
    with open(config_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'ss.json'
